var gameImages = {
    //background
    //ground
    glass1: 'img/background/ground/01.png',
    stone1: 'img/background/ground/02.png',
    stone2: 'img/background/ground/03.png',
    sea1: 'img/background/ground/09.png',
    //thing
    tree1: 'img/background/thing/01.png',

    //player2
    //stand
    idle1: 'img/player2/stand/01.png',
    idle2: 'img/player2/stand/02.png',
    idle3: 'img/player2/stand/03.png',
    idle4: 'img/player2/stand/04.png',
    idle5: 'img/player2/stand/05.png',
    idle6: 'img/player2/stand/06.png',
    idle7: 'img/player2/stand/07.png',
    idle8: 'img/player2/stand/08.png',
    idle9: 'img/player2/stand/09.png',
    idle10: 'img/player2/stand/10.png',
    idle11: 'img/player2/stand/11.png',
    idle12: 'img/player2/stand/12.png',
    idle13: 'img/player2/stand/13.png',
    idle14: 'img/player2/stand/14.png',
    idle15: 'img/player2/stand/15.png',
    idle16: 'img/player2/stand/16.png',
    idle17: 'img/player2/stand/17.png',
    idle18: 'img/player2/stand/18.png',
    idle19: 'img/player2/stand/19.png',
    idle20: 'img/player2/stand/20.png',
    idle21: 'img/player2/stand/21.png',
    idle22: 'img/player2/stand/22.png',
    idle23: 'img/player2/stand/23.png',
    idle24: 'img/player2/stand/24.png',
    idle25: 'img/player2/stand/25.png',
    idle26: 'img/player2/stand/26.png',
    idle27: 'img/player2/stand/27.png',
    idle28: 'img/player2/stand/28.png',
    idle29: 'img/player2/stand/29.png',
    idle30: 'img/player2/stand/30.png',
    idle31: 'img/player2/stand/31.png',
    idle32: 'img/player2/stand/32.png',
    //walk up
    walkup1: 'img/player2/run_up/01.png',
    walkup2: 'img/player2/run_up/02.png',
    walkup3: 'img/player2/run_up/03.png',
    walkup4: 'img/player2/run_up/04.png',
    walkup5: 'img/player2/run_up/05.png',
    walkup6: 'img/player2/run_up/06.png',
    walkup7: 'img/player2/run_up/07.png',
    walkup8: 'img/player2/run_up/08.png',
    walkup9: 'img/player2/run_up/09.png',
    walkup10: 'img/player2/run_up/10.png',
    walkup11: 'img/player2/run_up/11.png',
    walkup12: 'img/player2/run_up/12.png',
    walkup13: 'img/player2/run_up/13.png',
    walkup14: 'img/player2/run_up/14.png',
    //walk down
    walkdown1: 'img/player2/run_down/01.png',
    walkdown2: 'img/player2/run_down/02.png',
    walkdown3: 'img/player2/run_down/03.png',
    walkdown4: 'img/player2/run_down/04.png',
    walkdown5: 'img/player2/run_down/05.png',
    walkdown6: 'img/player2/run_down/06.png',
    walkdown7: 'img/player2/run_down/07.png',
    walkdown8: 'img/player2/run_down/08.png',
    walkdown9: 'img/player2/run_down/09.png',
    walkdown10: 'img/player2/run_down/10.png',
    walkdown11: 'img/player2/run_down/11.png',
    walkdown12: 'img/player2/run_down/12.png',
    walkdown13: 'img/player2/run_down/13.png',
    walkdown14: 'img/player2/run_down/14.png',
    //walk left
    walkleft1: 'img/player2/run_left/01.png',
    walkleft2: 'img/player2/run_left/02.png',
    walkleft3: 'img/player2/run_left/03.png',
    walkleft4: 'img/player2/run_left/04.png',
    walkleft5: 'img/player2/run_left/05.png',
    walkleft6: 'img/player2/run_left/06.png',
    walkleft7: 'img/player2/run_left/07.png',
    walkleft8: 'img/player2/run_left/08.png',
    walkleft9: 'img/player2/run_left/09.png',
    walkleft10: 'img/player2/run_left/10.png',
    walkleft11: 'img/player2/run_left/11.png',
    walkleft12: 'img/player2/run_left/12.png',
    walkleft13: 'img/player2/run_left/13.png',
    walkleft14: 'img/player2/run_left/14.png',
    //walk right
    walkright1: 'img/player2/run_right/01.png',
    walkright2: 'img/player2/run_right/02.png',
    walkright3: 'img/player2/run_right/03.png',
    walkright4: 'img/player2/run_right/04.png',
    walkright5: 'img/player2/run_right/05.png',
    walkright6: 'img/player2/run_right/06.png',
    walkright7: 'img/player2/run_right/07.png',
    walkright8: 'img/player2/run_right/08.png',
    walkright9: 'img/player2/run_right/09.png',
    walkright10: 'img/player2/run_right/10.png',
    walkright11: 'img/player2/run_right/11.png',
    walkright12: 'img/player2/run_right/12.png',
    walkright13: 'img/player2/run_right/13.png',
    walkright14: 'img/player2/run_right/14.png',
};

var config = {
  player: {
    _comment: 'player的属性配置',
    range: {
      min: 1,
      max: 60,
    },
    walkSpeed: 2,
    runSpeed: 4,
  },
  animation_cooldown: {
    _comment: '动图切换速度',
    range: {
      min: 1,
      max: 60,
    },
    value: 4,
  },
};
